name: hello-github-actions
# 触发 workflow 的事件
on:
  workflow_dispatch:
  push:
    # 分支随意
    branches:
      - master
# 一个workflow由执行的一项或多项job
jobs:
  # 一个job任务，任务名为build
  build:
    #运行在最新版ubuntu系统中
    runs-on: ubuntu-latest
    #步骤合集
    steps:
      #新建一个名为checkout_actions的步骤
      - name: checkout_actions
        #使用checkout@v2这个action获取源码
        uses: actions/checkout@v3
      - name: commit push
        #执行执行某个shell命令或脚本
        run:
          ls
          ./build/build_img.sh cumebox2
